#! /usr/bin/env ruby
hitch = system("which hitch")
if hitch
  puts "\e\[32m"
  puts `hitch`
  puts "\e\[0m"
  puts "If that ain't right do the following:"
  puts
  puts "$ hitch pair1 pair2"
  puts %Q{$ git commit --amend --author="`hitch`"}
  puts
end
